[package]
name = 'Cetue-AMM'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '72421d32d77f1877ded478e96f5b95914de1df91'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
cetus_amm = "0x2345"
